### ISSUE TITLE
Problemas com vários clicks simultâneos

### ISSUE THREAD

**Issue by oKaioP** [becastal/buSnake#1]
Quando são precionadas 2 teclas de mudar de direção ao mesmo tempo o jogo registra como se você tivesse batido em si mesmo, por exemplo apertar **A** para ir reto para a esquerda e apertar **S** e **D** rapidamente irá fazer seu trem crashar.

**Comment by becastal** [comment]
Problema resolvido. Agora tu so consegue mudar de direcao uma vez por atualizacao.
